### PR TITLE
Created closest_distance.cpp

### PR DESCRIPTION
**Pull request by escher-m**
Given an array of points in 2D plane, this program uses Divide and Conquer method to find the closest pair of points.

### CODE REVIEW

**Comment by escher-m** [comment]
Hi,
@atyant-yadav my PR was marked invalid before the 2 week maturity period. What do I do?

**Review by atyant-yadav — APPROVED** [review]

**Comment by atyant-yadav** [comment]
@escher-m check now and let me know.

**Comment by escher-m** [comment]
It says 

> Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by atyant-yadav** [comment]
The rep has "hacktoberfest" topic and i have marked all PR's as "hacktoberfest-accepted".
So let me know if i can do something for it. @escher-m

**Pull request merged**
